" ErgoVim
" =======



" ==== Personal Customizations ====

" Interface
set number
set ruler
set laststatus=2
set showcmd
set showmode
set wrap!
set mouse=a

" Tabs
set ai
set expandtab
set tabstop=4
set shiftwidth=4

" Search
set hlsearch
set ignorecase
set incsearch

" Misc.
set ve+=onemore
set backspace=indent,eol,start
set cpo-=<
set nocompatible
set hidden






" ==== Modes ====

" Temporary Normal Mode
" TODO
inoremap <C-L>  <C-O>

" Console
noremap  `      :
noremap  ~      Q




" ==== Navigation ====

" Basic Cursor Move
noremap  a      h
noremap  d      l
noremap  w      k
noremap  s      j

" Word and Block Move
noremap  q      b
noremap  e      w
noremap  r      {
noremap  f      }

noremap  Q      B
noremap  E      W
noremap  R      (
noremap  F      )

noremap  gq     B

" Page Move
noremap  W      <C-B> 
noremap  S      <C-F> 

" End
noremap  t      el
noremap  T      El

noremap  A      ^
noremap  D      g_l
noremap  <C-A>  0
noremap  <C-D>  $l
noremap  <C-W>  gg
noremap  <C-S>  G

" Mark (only 1 register, for fast navigation, otherwise it's too clunky to be useful
noremap  bi      ma
noremap  bb      `a     
noremap  B       `a     




" ==== Edit ====

" Insert
noremap  l      i
noremap  ll     i
noremap  L      i

noremap  p      r
noremap  P      ~

noremap  ln     a

noremap  lk     R

noremap  li     S
noremap  lI     s

noremap  lj     c

noremap  lja    c^
noremap  ljd    cg_
noremap  ljw    c(
noremap  ljs    c)

noremap  ljA    c0
noremap  ljD    c$
noremap  ljW    cgg
noremap  ljS    cG

noremap  la     I
noremap  ld     g_li
noremap  lw     O
noremap  ls     o

noremap  lA     gI
noremap  lD     A

noremap  lq     bi
noremap  le     eli
noremap  lr     {i
noremap  lf     }i

noremap  lQ     Bi
noremap  lE     Eli
noremap  lR     (i
noremap  lF     )i

" Numbers
noremap  =      <C-A>
noremap  -      <C-X>

noremap  +      g<C-A>
noremap  _      g<C-X>

" Seletion
noremap  m      v

noremap  M      V
noremap  MM     <C-V>

noremap  MI     {v}
noremap  Mi     (v)
noremap  ML     0v$h
noremap  MA     ggvG$

vnoremap j      d
vnoremap i      y

vnoremap la     I
vnoremap ld     A

vnoremap <Tab>    >
vnoremap <S-Tab>  <

" Delete
noremap  k      "_X
noremap  K      "_x
vnoremap k      "_x

" Cut
nnoremap j      d
nnoremap J      J
nnoremap <C-J>  gJ

nnoremap jj     dd

nnoremap ja     d^
nnoremap jd     dg_
nnoremap jw     d(
nnoremap js     d)

nnoremap jA     d0
nnoremap jD     d$
nnoremap jW     dgg
nnoremap jS     dG

nnoremap jN     dn
nnoremap jn     dN



" Copy
nnoremap i      y
nnoremap I      Y
nnoremap ii     Y

nnoremap ia     y^
nnoremap id     yg_
nnoremap iw     y(
nnoremap is     y)

nnoremap iA     y0
nnoremap iD     y$
nnoremap iW     ygg
nnoremap iS     yG

nnoremap in     yn
nnoremap in     yn

" Paste
noremap  o      p
noremap  O      P


" Unde/Redo
noremap  u      u
noremap  U      <C-R>

noremap  y      :earlier 
noremap  Y      :later 

" Repeat
noremap  h      .

" Indentation
nnoremap <Tab>     >>
nnoremap <S-Tab>   <<

" Space Action
noremap  <Return>    i<Return><Esc>
noremap  <S-Return>  O<ESC>j

noremap  <Space>     i<Space><Esc>l
noremap  <S-Space>   i<Tab><Esc>l

noremap  <BS>        k"_dd

" TODO: not quite right
nnoremap j<Space>a   gEldw
nnoremap j<Space>d   WgEldw
nnoremap j<Space>w   {{}d)
nnoremap j<Space>s   {}d)


" Text Object
nnoremap jkq  di[
nnoremap jlq  da[

nnoremap jkw  di{
nnoremap jlw  da{

nnoremap jke  di(
nnoremap jle  da(

nnoremap jkr  di<
nnoremap jlr  da<

nnoremap jka  di"
nnoremap jla  da"

nnoremap jks  di'
nnoremap jls  da'

nnoremap jkd  di`
nnoremap jld  da`

nnoremap jkf  dit
nnoremap jlf  dat

nnoremap jkz  diw
nnoremap jlz  daw

nnoremap jkx  diW
nnoremap jlx  daW

nnoremap jkc  dis
nnoremap jlc  das

nnoremap jkv  dip
nnoremap jlv  dap


nnoremap ikq  yi[
nnoremap ilq  ya[

nnoremap ikw  yi{
nnoremap ilw  ya{

nnoremap ike  yi(
nnoremap ile  ya(

nnoremap ikr  yi<
nnoremap ilr  ya<

nnoremap ika  yi"
nnoremap ila  ya"

nnoremap iks  yi'
nnoremap ils  ya'

nnoremap ikd  yi`
nnoremap ild  ya`

nnoremap ikf  yit
nnoremap ilf  yat

nnoremap ikz  yiw
nnoremap ilz  yaw

nnoremap ikx  yiW
nnoremap ilx  yaW

nnoremap ikc  yis
nnoremap ilc  yas

nnoremap ikv  yip
nnoremap ilv  yap




" ==== Auto-complete ====
" TODO
inoremap <S-Tab>    <C-X><C-I>
inoremap <S-Return> <C-N>





" ==== Registers ====
" TODO




" ==== Search ====
noremap  N     n
noremap  n     N

noremap  nl    /
noremap  nk    :noh<Return>

noremap  ni    #*
noremap  nI    y/<C-R>"<Esc>N

" TODO
noremap  nj    :s//
noremap  nJ    :%s//

noremap  no    &n
noremap  <C-N> &n

noremap  ns    /
noremap  nw    ?

noremap  na    F
noremap  nd    f
noremap  nA    T
noremap  nD    t

noremap  nq    ,
noremap  ne    ;



" ==== Macro ====
" TODO
noremap  <C-`> qa
noremap  H     @a




" ==== External ====
" TODO
noremap  gg     !k
noremap  G      !!






" ==== Folding ====
" TODO: not really useful, hard to type
"noremap  Z     <NOP>
"noremap  ZZ    zf
"noremap  ZL    zo
"noremap  ZK    zR




" ==== Buffer Management ====

" ---- Buffer ---- 
noremap  z     <NOP>

noremap  zz    :bn<Return>
noremap  Z     :bn<Return>

noremap  zd    :bn<Return>
noremap  za    :bp<Return>
noremap  zw    :bfirst<Return>
noremap  zs    :blast<Return>

noremap  zl    :buffer<Space>
noremap  zj    :ball<Return>
noremap  zk    :bd<Space>
noremap  zn    :badd<Space>

" ---- Window ---- 
noremap  x     <NOP>

noremap  xx    <C-W>w
noremap  X     <C-W>w

noremap  xl    <C-W>o
noremap  xk    <C-W>c

noremap  xA   <C-W>h
noremap  xD   <C-W>l
noremap  xW   <C-W>k
noremap  xS   <C-W>j

noremap  xo    <C-W>=

noremap  xa    <C-W>10<
noremap  xd    <C-W>10>
noremap  xw    :res +5<return>
noremap  xs    :res -5<return>

noremap  xi    <NOP>

noremap  xia   <C-W>v<C-W>l
noremap  xid   <C-W>v
noremap  xiw   <C-W>s<C-W>j
noremap  xis   <C-W>s

noremap  xn    <NOP>

noremap  xc    <C-W>T

noremap  xna   :lefta<Space>vnew<Space>
noremap  xnd   :rightb<Space>vnew<Space>
noremap  xnw   :lefta<Space>new<Space>
noremap  xns   :rightb<Space>new<Space>

noremap  xj    <NOP>

noremap  xjj   <C-W>x

noremap  xjq   <C-W>R
noremap  xje   <C-W>r

noremap  xja   <C-W>H
noremap  xjd   <C-W>L
noremap  xjw   <C-W>K
noremap  xjs   <C-W>J

" ---- Tab ---- 
noremap  c     <NOP>

noremap  C     :tabnext<Return>
noremap  cc    :tabnext<Return>

noremap  ca    :tabprevious<Return>
noremap  cd    :tabnext<Return>
noremap  cw    :tabfirst<Return>
noremap  cs    :tablast<Return>

noremap  cn    :tabnew<Space>
noremap  ci    :tab split<Return>
noremap  cl    :tabonly<Return>
noremap  ck    :tabclose<Return>

noremap  cja   :-tabmove<Return>
noremap  cjd   :+tabmove<Return>
noremap  cjw   :0tabmove<Return>
noremap  cjs   :tabmove<Return>





" ==== Terminal ====  
" TODO: vim and neovim have different behaviours
noremap  v     <NOP>

noremap  vv                  :rightb<Space>term<Return>
noremap  V                   :rightb<Space>term<Return>

noremap  va    :lefta<Space>vertical<Space>term<Return>
noremap  vd   :rightb<Space>vertical<Space>term<Return>
noremap  vw                               :term<Return>
noremap  vs                  :rightb<Space>term<Return>

" If map terminal normal mode to <Esc>, every Shift-<Key> will break. Vim, why?
" Also, you can not change input position in terminal normal mode 
" so these C-<Key> movements are still nessasary
tnoremap <C-L> <C-\><C-N>
tnoremap <C-X> <C-W>w

tnoremap <C-A> <Left>
tnoremap <C-D> <Right>
tnoremap <C-W> <Up>
tnoremap <C-S> <Down>

tnoremap <C-Q> <C-Left>
tnoremap <C-E> <C-Right>
tnoremap <C-R> <C-Up>
tnoremap <C-F> <C-Down>

tnoremap <C-O> <C-W>""
tnoremap <C-K> <BS>

" ==== Command Line ====
cnoremap <C-L> <C-F>

cnoremap <C-A> <Left>
cnoremap <C-D> <Right>
cnoremap <C-W> <Up>
cnoremap <C-S> <Down>

cnoremap <C-Q> <C-Left>
cnoremap <C-E> <C-Right>
cnoremap <C-R> <C-Up>
cnoremap <C-F> <C-Down>

cnoremap <C-O> <C-R>"
cnoremap <C-K> <BS>




" ==== Diff ====
" TODO




" ==== Misc ====

" quick exit
noremap  <C-Q><C-Q><C-Q> :qa!<Return>


" input special keys
inoremap <C-^> <C-V>
cnoremap <C-^> <C-V>
tnoremap <C-^> <C-V>



" Function Keys
" TODO
noremap  <F1>          :set wrap!<Return>
inoremap <F1>     <C-O>:set wrap!<Return>

noremap  <F5>          :registers<Return>
inoremap <F5>     <C-O>:registers<Return>

noremap  <F6>          :marks<Return>
inoremap <F6>     <C-O>:marks<Return>

noremap  <F7>          :tags<Return>
inoremap <F7>     <C-O>:tags<Return>

noremap  <F8>          :ls<Return>
inoremap <F8>     <C-O>:ls<Return>



" Save Normal People
noremap  <C-Z>    u
noremap  <C-Y>    <C-R>

noremap  <C-F>    /

" TODO: clipboard on linux not working
noremap  <C-X>    "*d
noremap  <C-C>    "*y
noremap  <C-V>    "*p

inoremap <C-V>    <C-O>"*p
cnoremap <C-V>    <MiddleMouse>
tnoremap <C-V>    <C-W>"*



" Trash Can 

cnoremap <C-Q> <NOP>
tnoremap <C-Q> <NOP>


